/*
 * Created by @tranphuquy19 on 10/12/2019
 * Email: tranphuquy19@gmail.com
 */
const USER_LOGIN_PASS = 'USER_LOGIN_PASS';
const USER_LOGIN_GOOGLE = 'USER_LOGIN_GOOGLE';
const USER_LOGIN_FACEBOOK = 'USER_LOGIN_FACEBOOK';
const USER_LOGIN_QR_CODE = 'USER_LOGIN_QR_CODE';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_REGISTER = 'USER_REGISTER';

const GET_ALL_SONGS = "GEL_ALL_SONGS";


export {
    USER_LOGIN_PASS,
    USER_LOGIN_FACEBOOK,
    USER_LOGIN_GOOGLE,
    USER_LOGIN_QR_CODE,

    USER_REGISTER,
    USER_LOGOUT,

    GET_ALL_SONGS
}
